language: android

before_install:
  - chmod +x gradlew

android:
  components:
    - build-tools-24.0.1
    - android-23
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository